//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ContactId { get; set; }
        public int UserId { get; set; }
        public string Information { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
