//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Contributions = new HashSet<Contribution>();
            this.Disbursements = new HashSet<Disbursement>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public int CategoryId { get; set; }
        public string Location { get; set; }
        public int ContactId { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public int AmountNeeded { get; set; }
        public int Revenue { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Contribution> Contributions { get; set; }
        public virtual ICollection<Disbursement> Disbursements { get; set; }
    }
}
